# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -g

# Source and output
SRC_DIR = src
HDR_DIR = include
BUILD_DIR = build
OUT = $(BUILD_DIR)/graph

# All C source files
SRC = $(wildcard $(SRC_DIR)/*.c) $(wildcard $(HDR_DIR)/*.c)
OBJ = $(patsubst %.c, $(BUILD_DIR)/%.o, $(subst $(SRC_DIR)/,,$(SRC)))

# Include directories
INCLUDES = -I$(SRC_DIR)
INCLUDES = -I$(HDR_DIR)


# Default target
all: $(OUT)

# Link object files into final binary
$(OUT): $(OBJ)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -o $@ $^

# Compile each .c to .o
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

$(BUILD_DIR)/include/%.o: $(HDR_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

# Clean build artifacts
clean:
	rm -rf $(BUILD_DIR)
